/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package coin.changer;

import org.junit.Test;

import java.util.ArrayList;
import java.util.List;

import static org.junit.Assert.*;

public class CoinChangerTest {
    @Test public void testReturnsASinglePennyForOne() {
        CoinChanger changer = new CoinChanger();
        List<Integer> expectedOutput = new ArrayList<>(List.of(1));
        assertEquals("should return a single penny for one", expectedOutput, changer.change(1));
    }

    @Test public void testReturnsASingle2pForTwo() {
        CoinChanger changer = new CoinChanger();
        List<Integer> expectedOutput = new ArrayList<>(List.of(2));
        assertEquals("should return a single 2p for two", expectedOutput, changer.change(2));
    }

    @Test public void testReturns2pAndAPennyForThree() {
        CoinChanger changer = new CoinChanger();
        List<Integer> expectedOutput = new ArrayList<>(List.of(2, 1));
        assertEquals("should return 2p and a penny for three", expectedOutput, changer.change(3));
    }

    @Test public void testReturnsTwo2psForFour() {
        CoinChanger changer = new CoinChanger();
        List<Integer> expectedOutput = new ArrayList<>(List.of(2, 2));
        assertEquals("should return two 2ps for four", expectedOutput, changer.change(4));
    }

    @Test public void testReturnsASingle5pForTen() {
        CoinChanger changer = new CoinChanger();
        List<Integer> expectedOutput = new ArrayList<>(List.of(5));
        assertEquals("should return a single 5p for five", expectedOutput, changer.change(5));
    }
}
